name: crux
description: "CRUX - Videoconference with YouTube Live - Powered by ZegoCloud"

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter

  # Firebase & Authentication
  firebase_core: ^3.6.0
  firebase_auth: ^5.3.1
  cloud_firestore: ^5.4.4
  google_sign_in: ^6.2.1

  # Permissions & Media
  permission_handler: ^11.3.0
  image_picker: ^1.0.8

  # Storage
  shared_preferences: ^2.3.2

  # Internationalization
  intl: ^0.20.2

  # Networking
  http: ^1.1.0

  # ZegoCloud - VERSIONS FINALES ET STABLES
  zego_uikit_prebuilt_video_conference: ^2.10.1
  zego_uikit: ^2.10.1

  # UI
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
