pluginManagement {
    val flutterSdkPath = run {
        val properties = java.util.Properties()
        file("local.properties").inputStream().use { properties.load(it) }
        val flutterSdkPath = properties.getProperty("flutter.sdk")
        requireNotNull(flutterSdkPath) { "flutter.sdk not set in local.properties" }
        flutterSdkPath
    }
    includeBuild("$flutterSdkPath/packages/flutter_tools/gradle")
    repositories {
        google()
        mavenCentral()
        gradlePluginPortal()
    }
}

// No flutter-plugin-loader — it internally evaluates :app early,
// causing flutter-gradle-plugin's afterEvaluate to throw.
// Plugin subprojects are included manually below instead.

include(":app")
rootProject.name = "crux"

// Manually include Flutter plugin subprojects from .flutter-plugins
// (generated by flutter pub get — path relative to Android project root)
val flutterPluginsFile = File(rootDir.parentFile, ".flutter-plugins")
if (flutterPluginsFile.exists()) {
    val pluginProps = java.util.Properties()
    flutterPluginsFile.inputStream().use { pluginProps.load(it) }
    pluginProps.forEach { (pluginName, pluginPath) ->
        val pluginDir = File("$pluginPath/android").canonicalFile
        if (pluginDir.exists()) {
            include(":$pluginName")
            project(":$pluginName").projectDir = pluginDir
        }
    }
}
